Fixed conformance_arena_constraints test failure with no NUMA hardware.
On a system without NUMA support, like GNU Hurd, the test would fail like this:

[doctest] doctest version is "2.4.12"
[doctest] run with "--help" for options
===============================================================================
test/conformance/conformance_arena_constraints.cpp:44:
TEST CASE:  Test NUMA topology traversal correctness

test/conformance/conformance_arena_constraints.cpp:54: FATAL ERROR: REQUIRE( pos != numa_nodes_info.end() ) is NOT correct!
  values: REQUIRE( {?} != {?} )
  logged: Wrong, extra or repeated NUMA node index detected.

===============================================================================
[doctest] test cases:  5 |  4 passed | 1 failed | 0 skipped
[doctest] assertions: 27 | 26 passed | 1 failed |
[doctest] Status: FAILURE!

With the fix in place, the test succeed.

Fixes #2039